[package]
name = "sudoku-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudoku-solver-lib = { path = "../lib" }
rand = "0.8.5"