name: 🦀 Checks

on:
  push:
    branches: ["main"]
  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: 🦀 Check rust
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 📋 Run tests
        run: cargo test --color=always
